server:
  port: 8001

logging:
  level:
     com.eocencle.dasislcy: debug

spring:
  application:
     name: dasislcy
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-57uroysm.bj.tencentcdb.com:10160/dasislcy?characterEncoding=utf8&useSSL=false
    username: dasislcy
    password: data1234
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    charset: UTF-8
    allow-request-override: false
    cache: false
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false

mybatis:
   config-location: classpath:mybatis/mybatis-config.xml
   mapper-locations: classpath:mybatis/mapper/*.xml
   type-aliases-package: com.eocencle.dasislcy.entity

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

servlet:
  multipart:
    max-file-size: 100Mb
    max-request-size: 100Mb
    session:
      timeout: -100000  # 十天
    cookie:
      max-age: 130000s

#自定义
main:
  page: index



