server:
  port: 8001

logging:
  level:
     com.eocencle.dasislcy: debug

spring:
  application:
     name: dasislcy
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:10160/dasislcy?characterEncoding=utf8&useSSL=false
    username: username
    password: password
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    charset: UTF-8
    allow-request-override: false
    cache: false
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false

mybatis:
   config-location: classpath:mybatis/mybatis-config.xml
   mapper-locations: classpath:mybatis/mapper/*.xml
   type-aliases-package: com.eocencle.dasislcy.entity

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#自定义
main:
  page: index
  upload-dir: /usr/local/dasislcy/file/upload/subject
  template-dir: /usr/local/dasislcy/file/template
  answersheet-dir: /usr/local/dasislcy/file/upload/answersheet
#  upload-dir: E:/test/file
#  template-dir: E:/test/file
#  answersheet-dir: F:/test/file



